### ISSUE TITLE
Image load: Image asset not found?

### ISSUE THREAD

**Issue by morganeg** [CoralMapping/gee-mapping-source#1]
Hello there,
I tried to download & replicate code in Earth Engine, but some image assets are not loading...
Have I missed a step in replicating the scripts in Earth Engine Code Editor?
See screenshots attached.
<img width="1061" alt="Screen Shot 2020-05-15 at 2 26 25 PM" src="https://user-images.githubusercontent.com/18084484/82050247-16452300-96b8-11ea-814c-59874e1e4a5c.png">

**Comment by mitchest** [comment]
wow sorry! i must have missed this ages ago. Yes unfortunately the Planet Dove reflectance data is not open access. If you would like to replicate it, you would just have to substitute the image products with your own - you could make a entry like in the [reef_params ](https://github.com/CoralMapping/gee-mapping-source/blob/master/Modules/reef_params) module with paths to your own data or data you have access to, and then try running the scripts.
