### ISSUE TITLE
GBR Review Geomorphic v1

### ISSUE THREAD

**Issue by ChrisRoelf** [CoralMapping/gee-mapping-source#3]
Mitch could check this @mitchest 
- [ ] 1.	Any thoughts for missing data on reef flat (e.g. one tree)

- [ ] 2.	RC:  surrounded by ORF should be ORF, Slivers see heron, RC nicely removed from middle of reefs by the way, check showers reef RC in deep water does not make sense

- [ ] 3.	BRS: surrounded by ORF should be SL or DL, BRS and DL mix, not sure how to explain and if we can do something about it.

- [ ] 4.	SS: SS steep and hard substrate, BSL can be steep can have hard and soft substrate, sometime in middle lagoon where it does not look steep at al, consider SS neighbouring BRS to make BRS (with the thought they are bot sheltered, it mostly occure on the deep site of back reef slope where it just get steeper but still sandy bottom). If SL surrounded by BRS then SL is BRS

- [ ] 5.	Reefs to check: square reef, see IRF into RS, check ross reef SL in middle of lagoon

- [ ] 6.	RS and BRS and Plateau see deeper reefs far north

**Comment by mitchest** [comment]
1. Missing data on reef flat is missing ALL data, so not a lot to do except manual crayons
2. Some RC cleaned up (really deep back to deep, up to 10m to slope) - the reason for the errors was an odd consequence of some cleanup routines, as it was not RC in the raw classification
3. Small BRS noise removed
4. ... i think BRS cleaned as much as possible now
5. also improved as much as possible
6. rule for deep/gentle slope -> plateau

These are the rule i implemented:

- Clean up of noise/small object as a last step
- Depth cutoffs for RC as above
- BRS > 10m & BRS < 10 degress == PL

i checked occurence of SS in geomorphic & Sand in benthic - but it essentially never occurs, so no need for a rule.
